---
title: "EDA"
output: html_document
---

# Setting{.tabset .tabset-fade .tabset-pills}

## knitr option

```{r reset, include=FALSE}
# reset
rm(list = ls())
```

```{r set up, message=FALSE}
# set directory
setwd("~/Desktop/Elo_kaggle/") 
# max.print 
options(max.print="200", digits=5)
# Global options
library(knitr)
opts_chunk$set(echo=TRUE,
               # cache = FALSE,
	             prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

## Library package

```{r package, message=FALSE}
library(tidyverse)
library(summarytools) # summary easily for EDA
```

## Load funciton

```{r}

```

## ggplot themes

```{r}
# set ggplot theme
library(ggplot2)
library(ggthemes)
# theme_set(theme_classic(base_size = 14, base_family = "HiraKakuPro-W3")) # 日本語用
theme_set(theme_classic(base_size = 18,base_family = "Helvetica")) # 英語用
```

## Import csv

- Import raw data from `csv/~.csv`
- Define missing values: na = c("XNA","NA","","NaN","?",...)
- Convert charcter's columns into factor's columns 
- Delete duplicate column names and change them to lower case

```{r cache=TRUE}
# 訓練データ, テストデータ
train <- read_csv("~/Desktop/Elo_kaggle/input/raw/train.csv",
                  na = c("XNA","NA","","NaN","?")) %>% 
  mutate_if(is.character, funs(factor(.))) 
test <- read_csv("~/Desktop/Elo_kaggle/input/raw/test.csv",
                  na = c("XNA","NA","","NaN","?")) %>% 
  mutate_if(is.character, funs(factor(.))) 
# 取引情報データ
transactions <- read_csv("~/Desktop/Elo_kaggle/input/raw/historical_transactions.csv",
                         na = c("XNA","NA","","NaN","?")) %>% 
  mutate_if(is.character, funs(factor(.))) 
new_transactions <- read_csv("~/Desktop/Elo_kaggle/input/raw/new_merchant_transactions.csv",
                             na = c("XNA","NA","","NaN","?")) %>% 
  mutate_if(is.character, funs(factor(.))) 
# 加盟店情報
merchants <- read_csv("~/Desktop/Elo_kaggle/input/raw/merchants.csv",
                      na = c("XNA","NA","","NaN","?")) %>% 
  mutate_if(is.character, funs(factor(.))) 
# サブミットファイル
sample_submit <- read_csv("~/Desktop/Elo_kaggle/input/raw/sample_submission.csv",
                          na = c("XNA","NA","","NaN","?")) %>% 
  mutate_if(is.character, funs(factor(.))) 
```

# EDA{.tabset .tabset-fade .tabset-pills}

## glimpse 

```{r}
train %>% glimpse()
test %>% glimpse()
transactions %>% glimpse()
new_transactions %>% glimpse()
merchants %>% glimpse()
```

## summarytools

```{r}
dfSummary(train) %>% view(method = "render")
dfSummary(test) %>% view(method = "render")
dfSummary(transactions) %>% view(method = "render")
dfSummary(new_transactions) %>% view(method = "render")
dfSummary(merchants) %>% view(method = "render")
```


